# Generated by Django 5.2.8 on 2025-11-15 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
